apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: driver-server
  name: driver_server
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: driver-server
status:
  loadBalancer: {}
