apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: driver-server
  name: driver-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: driver-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: driver-server
    spec:
      containers:
        - env:
            - name: REDIS_ADDR
              value: redis:6379
          image: eu.gcr.io/cloudcomputing-386413/cc-driver-server
          name: driver_server
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
