apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: driver-client
  name: driver-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: driver-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: driver-client
    spec:
      containers:
        - env:
            - name: DRIVER_SERVICE_ADDR
              value: driver_server:8081
          image: eu.gcr.io/cloudcomputing-386413/cc-driver-client
          name: driver_client
          resources: {}
      restartPolicy: Always
status: {}
