apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ride-server
  name: ride_server
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: ride-server
status:
  loadBalancer: {}
