// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: ride.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RideClient is the client API for Ride service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RideClient interface {
	Start(ctx context.Context, in *LocationMetadata, opts ...grpc.CallOption) (*StartRideResponse, error)
}

type rideClient struct {
	cc grpc.ClientConnInterface
}

func NewRideClient(cc grpc.ClientConnInterface) RideClient {
	return &rideClient{cc}
}

func (c *rideClient) Start(ctx context.Context, in *LocationMetadata, opts ...grpc.CallOption) (*StartRideResponse, error) {
	out := new(StartRideResponse)
	err := c.cc.Invoke(ctx, "/Ride/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RideServer is the server API for Ride service.
// All implementations must embed UnimplementedRideServer
// for forward compatibility
type RideServer interface {
	Start(context.Context, *LocationMetadata) (*StartRideResponse, error)
	mustEmbedUnimplementedRideServer()
}

// UnimplementedRideServer must be embedded to have forward compatible implementations.
type UnimplementedRideServer struct {
}

func (UnimplementedRideServer) Start(context.Context, *LocationMetadata) (*StartRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedRideServer) mustEmbedUnimplementedRideServer() {}

// UnsafeRideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RideServer will
// result in compilation errors.
type UnsafeRideServer interface {
	mustEmbedUnimplementedRideServer()
}

func RegisterRideServer(s grpc.ServiceRegistrar, srv RideServer) {
	s.RegisterService(&Ride_ServiceDesc, srv)
}

func _Ride_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ride/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideServer).Start(ctx, req.(*LocationMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

// Ride_ServiceDesc is the grpc.ServiceDesc for Ride service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ride_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ride",
	HandlerType: (*RideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Ride_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ride.proto",
}
